export const environmentalMetricMap = {
  energyConsumption: "energy_consumption_mwh",
  scope1Emissions: "ghg_scope1_tco2e",
  scope2Emissions: "ghg_scope2_tco2e",
  scope3Emissions: "ghg_scope3_tco2e",
  renewableEnergyPercentage: "renewable_energy_percentage",
  waterWithdrawal: "water_withdrawal_m3",
  waterDischarge: "water_discharge_m3",
  wasteGenerated: "waste_generated_tonnes",
  tailingsProduced: "mine_tailings_tonnes",
  landRehabilitated: "land_rehabilitated_hectares",
  biodiversityImpact: "biodiversity_impact_score",
  medicalWaste: "medical_waste_tonnes",
  pharmaceuticalEmissions: "pharmaceutical_emissions_tco2e",
  industrialWaste: "industrial_waste_tonnes",
  manufacturingEmissions: "manufacturing_emissions_tco2e",
  productionEnergyIntensity: "production_energy_intensity",
};
